### ISSUE TITLE
Marsad Egypt publication sync with Libya and Palestine

### ISSUE THREAD

**Issue by manshanssen** [ActivateMedia/Marsad#68]
@rexromae and @therealmyth I updated the Marsad Egypt publication section yesterday with this publication: http://www.marsad.eg/en/publication/the-role-of-good-security-sector-governance-in-countering-violent-extremism-in-the-mena-region/ however, today when I checked Marsad Libya it had not been updated. Could you look into this please?

**Comment by rexromae** [comment]
Hi @manshanssen, I have synchronized the 2 websites, I have also set up a scheduled task on marsad.ly to import the publications every 12 hours, Monday to Friday. It should auto-sync the websites from now. Sorry for the delay!

**Comment by manshanssen** [comment]
@rexromae ok, great! please dont forget that it should be updated on this one as well: http://test.marsad.info/en/publications/ and this one: http://security-ly.activatemedia.com/publications-loi

**Comment by manshanssen** [comment]
@rexromae I just noticed that the following publication http://www.marsad.ly/en/publication/aide-memoire-visiting-detention-places-in-tunisia/ has the incorrect picture added to it, the pic is correct on Marsad Egypt and Palestine... the PDF link doesnt work either. Could you please amend this urgently?

**Comment by rexromae** [comment]
Hi @manshanssen, issue solved. The problem was caused by the fact that, the cover images for the 2 publications have the same filename "Untitled.png". If it happens again, the solution is upload on the master website (EG) the cover with a SEO friendly name (eg: aide-memoire-tunisie.png) in this way we get indexed on Google Images and we avoid conflicts like this. You can wait the next update or force to reaload the images entering this URL (http://marsad.ly/index.php?__api=1&import_publications_thumbnails=1).

**Comment by manshanssen** [comment]
@rexromae excellent, however, the PDF link onthis page: http://www.marsad.ly/en/publication/aide-memoire-visiting-detention-places-in-tunisia/ still doesnt work...

**Comment by rexromae** [comment]
The problem should be fixed.

**Comment by manshanssen** [comment]
@rexromae the sync with Marsad palestine is still not up to date...

**Comment by rexromae** [comment]
The reason is that Marsad Palestine doesn't have the auto-update for the test site. We will setup a auto-scheduled script to import the publications on the PS live website.
